In [1]:
import os
import pandas as pd
import pm4py
import numbers
import decimal
import pandas.api.types as ptypes
import numpy as np
from pm4py.algo.filtering.log.cases import case_filter
from pm4py.algo.filtering.pandas.timestamp import timestamp_filter
from pm4py.algo.filtering.log.start_activities import start_activities_filter
from pm4py.algo.filtering.log.end_activities import end_activities_filter
from pm4py.algo.filtering.pandas.variants import variants_filter
from pm4py.objects.log.util import dataframe_utils
from pm4py.objects.conversion.log import converter as log_converter
from pm4py.util import constants
from pm4py.statistics.traces.pandas import case_statistics
from pm4py.algo.filtering.log.attributes import attributes_filter
from numpy.linalg import norm
from pm4py.objects.log.importer.xes import importer as xes_importer
from multiprocessing import Process, Queue, Pool, cpu_count
import multiprocessing
import random
import itertools
import functools
from sklearn.metrics.pairwise import euclidean_distances
from scipy.spatial.distance import cdist, pdist
from scipy.spatial import distance

In [37]:



#convert log file(in csv) to pandas dataframe

"""
QUESTIONS!
importing scheme

1.the major attributes : Case ID, Activity, Complete Timestamp, and org(resource or something)
They should be ordered such that the rest can be considered as case attributes
!!!!!!!this should be done either for xes or csv, also how to parse the given event log file such that
they can be managed in the form Case ID, Acitivity, Timestamp, and resource? is there any scheme to detect which colume
corresponds to which attribute?

2.importing method should deliver also the file path such that this program
can choose either xes or csv file converting

3. what is an empty value exists?

4. organize log file such that
caseid should be the first column
the others resource, timestamp

#It could make the whole process easy
5. allow user to select/organize columns by checking the name
??

Weakness:

1. still depending on the column orders
2. to often used the Case ID
3. def export_file(df, caseids, s_vci, n = 1): find the scheme s.t. 
n indicates unique selection, logarithmic, and division selection

"""

log_csv = pd.read_csv('../eventlogs/ItalianHelpdeskFinal.csv', sep=',')
log_csv = dataframe_utils.convert_timestamp_columns_in_df(log_csv)
param_keys={constants.PARAMETER_CONSTANT_CASEID_KEY: 'Case ID', 
    constants.PARAMETER_CONSTANT_ACTIVITY_KEY: 'Activity', 
            constants.PARAMETER_CONSTANT_TIMESTAMP_KEY: "Complete Timestamp"
           }
event_log = log_converter.apply(log_csv,parameters=param_keys)


#import xes file
#q = xes_importer.apply('../eventlogs/repairExample.xes')

#convert xes to dataframe
#dataframe = log_converter.apply(q, variant=log_converter.Variants.TO_DATA_FRAME)

,Case ID,Activity,org:resource,Complete Timestamp,seriousness,customer,product,seriousness_2,service_level,service_type,workgroup
0,Case 1,Assign seriousness,Value 1,2012-10-09 14:50:17+00:00,Value 1,Value 1,Value 1,Value 1,Value 1,Value 1,Value 1
1,Case 1,Take in charge ticket,Value 1,2012-10-09 14:51:01+00:00,Value 1,Value 1,Value 1,Value 1,Value 1,Value 1,Value 1
2,Case 1,Take in charge ticket,Value 2,2012-10-12 15:02:56+00:00,Value 1,Value 1,Value 1,Value 1,Value 2,Value 1,Value 1
3,Case 1,Resolve ticket,Value 1,2012-10-25 11:54:26+00:00,Value 1,Value 1,Value 1,Value 1,Value 2,Value 1,Value 1
4,Case 1,Closed,Value 3,2012-11-09 12:54:39+00:00,Value 1,Value 1,Value 1,Value 1,Value 2,Value 1,Value 1
5,Case 2,Assign seriousness,Value 4,2012-04-03 08:55:38+00:00,Value 1,Value 2,Value 2,Value 1,Value 2,Value 1,Value 1
6,Case 2,Take in charge ticket,Value 4,2012-04-03 08:55:53+00:00,Value 1,Value 2,Value 2,Value 1,Value 2,Value 1,Value 1
7,Case 2,Resolve ticket,Value 4,2012-04-05 09:15:52+00:00,Value 1,Value 2,Value 2,Value 1,Value 2,Value 1,Value 1
8,Case 2,Closed,Value 5,2012-05-19 09:00:28+00:00,Value 1,Value 2,Value 2,Value 1,Value 2,Value 1,Value 1
9,Case 3,Assign seriousness,Value 6,2010-10-29 10:14:06+00:00,Value 1,Value 3,Value 3,Value 2,Value 2,Value 1,Value 1
10,Case 3,Take in charge ticket,Value 7,2010-11-03 16:16:11+00:00,Value 1,Value 3,Value 3,Value 2,Value 2,Value 1,Value 1
11,Case 3,Resolve ticket,Value 7,2010-11-03 16:21:17+00:00,Value 1,Value 3,Value 3,Value 2,Value 2,Value 1,Value 1
12,Case 3,Closed,Value 5,2010-11-30 11:20:18+00:00,Value 1,Value 3,Value 3,Value 2,Value 2,Value 1,Value 1
13,Case 4,Assign seriousness,Value 8,2010-12-15 14:31:53+00:00,Value 1,Value 4,Value 3,Value 2,Value 2,Value 1,Value 1
14,Case 4,Take in charge ticket,Value 2,2010-12-16 08:01:07+00:00,Value 1,Value 4,Value 3,Value 2,Value 2,Value 1,Value 1
15,Case 4,Resolve ticket,Value 2,2010-12-16 08:08:19+00:00,Value 1,Value 4,Value 3,Value 2,Value 2,Value 1,Value 1
16,Case 4,Closed,Value 5,2011-02-12 14:40:42+00:00,Value 1,Value 4,Value 3,Value 2,Value 2,Value 1,Value 1
17,Case 5,Assign seriousness,Value 9,2012-04-03 13:08:32+00:00,Value 1,Value 5,Value 3,Value 2,Value 3,Value 1,Value 1
18,Case 5,Take in charge ticket,Value 10,2012-04-03 13:45:33+00:00,Value 1,Value 5,Value 3,Value 2,Value 3,Value 1,Value 1
19,Case 5,Resolve ticket,Value 10,2012-04-03 13:47:22+00:00,Value 1,Value 5,Value 3,Value 2,Value 3,Value 1,Value 1
20,Case 5,Take in charge ticket,Value 10,2012-04-03 14:15:02+00:00,Value 1,Value 5,Value 3,Value 2,Value 3,Value 1,Value 1
21,Case 5,Resolve ticket,Value 10,2012-04-03 16:07:28+00:00,Value 1,Value 5,Value 3,Value 2,Value 3,Value 1,Value 1
22,Case 5,Closed,Value 5,2012-05-25 13:10:28+00:00,Value 1,Value 5,Value 3,Value 2,Value 3,Value 1,Value 1
23,Case 6,Assign seriousness,Value 2,2011-10-25 15:13:58+00:00,Value 1,Value 6,Value 2,Value 1,Value 2,Value 1,Value 1
24,Case 6,Take in charge ticket,Value 2,2011-10-25 15:58:55+00:00,Value 1,Value 6,Value 2,Value 1,Value 2,Value 1,Value 1
25,Case 6,Resolve ticket,Value 2,2011-10-26 09:54:46+00:00,Value 1,Value 6,Value 2,Value 1,Value 2,Value 1,Value 1
26,Case 6,Closed,Value 5,2011-12-10 16:20:56+00:00,Value 1,Value 6,Value 2,Value 1,Value 2,Value 1,Value 1
27,Case 7,Assign seriousness,Value 1,2013-11-06 10:47:35+00:00,Value 1,Value 7,Value 1,Value 1,Value 2,Value 2,Value 2
28,Case 7,Assign seriousness,Value 1,2013-11-06 10:48:53+00:00,Value 1,Value 7,Value 1,Value 1,Value 2,Value 2,Value 2
29,Case 7,Assign seriousness,Value 2,2013-11-22 08:00:08+00:00,Value 1,Value 7,Value 1,Value 2,Value 2,Value 2,Value 2
...,...,...,...,...,...,...,...,...,...,...,...
21312,Case 4573,Resolve ticket,Value 14,2010-12-06 13:11:45+00:00,Value 1,Value 22,Value 3,Value 2,Value 2,Value 1,Value 1
21313,Case 4573,Closed,Value 5,2010-12-28 10:30:32+00:00,Value 1,Value 22,Value 3,Value 2,Value 2,Value 1,Value 1
21314,Case 4574,Assign seriousness,Value 8,2011-02-03 13:21:44+00:00,Value 1,Value 227,Value 2,Value 2,Value 2,Value 1,Value 1
21315,Case 4574,Take in charge ticket,Value 8,2011-02-03 13:22:06+00:00,Value 1,Value 227,Value 2,Value 2,Value 2,Value 1,Value 1
21316,Case 4574,Resolve ticket,Value 8,2011-02-04 08:27:08+00:00,Value 1,Value 227,Value 2,Value 2,Value 2,Value 1,Value 1
21317,Case 4574,Closed,Value 5,2011-04-03 12:30:31+00:00,Value 1,Value 227,Value 2,Value 2,Value 2,Value 1,Value 1
21318,Case 4575,Assign seriousness,Value 4,2013-03-06 14:38:46+00:00,Value 1,Value 211,Value 1,Value 1,Value 2,Value 1,Value 1
21319,Case 4575,Take in charge ticket,Value 2,2013-03-21 13:38:08+00:00,Value 1,Value 211,Value 1,Value 1,Value 2,Value 1,Value 1
21320,Case 4575,Wait,Value 9,2013-03-21 14:09:32+00:00,Value 1,Value 211,Value 1,Value 1,Value 2,Value 1,Value 1
21321,Case 4575,Resolve ticket,Value 9,2013-03-22 12:01:57+00:00,Value 1,Value 211,Value 1,Value 1,Value 2,Value 1,Value 1
21322,Case 4575,Closed,Value 3,2013-04-06 11:02:15+00:00,Value 1,Value 211,Value 1,Value 1,Value 2,Value 1,Value 1
21323,Case 4576,Assign seriousness,Value 2,2012-02-14 10:21:51+00:00,Value 1,Value 68,Value 1,Value 1,Value 2,Value 1,Value 1
21324,Case 4576,Take in charge ticket,Value 2,2012-02-14 10:22:10+00:00,Value 1,Value 68,Value 1,Value 1,Value 2,Value 1,Value 1
21325,Case 4576,Resolve ticket,Value 2,2012-02-14 11:32:51+00:00,Value 1,Value 68,Value 1,Value 1,Value 2,Value 1,Value 1
21326,Case 4576,Closed,Value 5,2012-03-16 10:30:16+00:00,Value 1,Value 68,Value 1,Value 1,Value 2,Value 1,Value 1
21327,Case 4577,Assign seriousness,Value 2,2010-03-24 15:28:51+00:00,Value 1,Value 204,Value 3,Value 1,Value 2,Value 1,Value 1
21328,Case 4577,Take in charge ticket,Value 2,2010-04-13 09:30:07+00:00,Value 1,Value 204,Value 3,Value 1,Value 2,Value 1,Value 1
21329,Case 4577,Resolve ticket,Value 2,2010-04-13 09:30:12+00:00,Value 1,Value 204,Value 3,Value 1,Value 2,Value 1,Value 1
21330,Case 4577,Closed,Value 5,2010-05-13 09:30:29+00:00,Value 1,Value 204,Value 3,Value 1,Value 2,Value 1,Value 1
21331,Case 4578,Assign seriousness,Value 1,2011-12-28 13:21:10+00:00,Value 1,Value 51,Value 8,Value 1,Value 2,Value 1,Value 1
21332,Case 4578,Resolve ticket,Value 1,2011-12-28 13:23:28+00:00,Value 1,Value 51,Value 8,Value 1,Value 2,Value 1,Value 1
21333,Case 4578,Closed,Value 5,2012-01-28 13:30:15+00:00,Value 1,Value 51,Value 8,Value 1,Value 2,Value 1,Value 1
21334,Case 4579,Assign seriousness,Value 9,2010-07-26 10:02:35+00:00,Value 1,Value 71,Value 3,Value 1,Value 3,Value 1,Value 1
21335,Case 4579,Take in charge ticket,Value 9,2010-07-26 13:31:59+00:00,Value 1,Value 71,Value 3,Value 1,Value 3,Value 1,Value 1
21336,Case 4579,Resolve ticket,Value 9,2010-07-26 13:32:11+00:00,Value 1,Value 71,Value 3,Value 1,Value 3,Value 1,Value 1
21337,Case 4579,Closed,Value 5,2010-09-02 10:11:00+00:00,Value 1,Value 71,Value 3,Value 1,Value 3,Value 1,Value 1
21338,Case 4580,Take in charge ticket,Value 6,2012-01-03 09:33:43+00:00,Value 1,Value 92,Value 3,Value 2,Value 2,Value 2,Value 1
21339,Case 4580,Wait,Value 6,2012-01-10 15:30:11+00:00,Value 1,Value 92,Value 3,Value 2,Value 2,Value 2,Value 1
21340,Case 4580,Resolve ticket,Value 6,2012-01-10 17:07:40+00:00,Value 1,Value 92,Value 3,Value 2,Value 2,Value 2,Value 1
21341,Case 4580,Closed,Value 5,2012-02-08 17:00:34+00:00,Value 1,Value 92,Value 3,Value 2,Value 2,Value 2,Value 1

## 1-Traversing the event log:

In [3]:
#filter variants from the given log_csv
#variants contains seriese objects that consist of Case ID, variant(a sequence of activities), and dtype
variants = case_statistics.get_variants_df(log_csv,
                                          parameters={constants.PARAMETER_CONSTANT_CASEID_KEY: "Case ID",
                                                      constants.PARAMETER_CONSTANT_ACTIVITY_KEY: "Activity"})
variants.describe(include='all')

stats = variants.describe(include='all')

variant_caseid = variants.copy()

#1. Filter cases sharing the same variant

#a. duplicate the case ids as an additional column
variant_caseid['Case IDs'] = variants.index

#b. set variant(sequence of acitvities) as the index
#-> exchange the index from case id to variant
# duplicated Case Ids contain the case Ids, the case Ids in the index is deleted
variant_caseid.set_index('variant', inplace=True)

#c. duplicate variant and store them as an additional column
variant_caseid['variant2'] = variant_caseid.index

#d. collect every case ids sharing the same variant
variant_caseid = list(variant_caseid.groupby("variant2")["Case IDs"].apply(list))

'\n\nvariants:\n\ncaseID Variant\ncase 1 abc\ncase 2 bcd \n.\n.\n.\n\nHowever we need\n\nVariant CaseID\nabc.    [Case 1, Case 3]\nbcd.    \n-> variant_caseid\n'

## 2-Distribution Computation:

In [10]:
#copy the dataframe
log_csv2 = log_csv.copy()

#just keep the last activity record
last_activities = log_csv2.drop_duplicates(subset=["Case ID"], keep = "last")

ccols = []
#keep the final returning case id
final_caseid = []

#start for loop to collect categorical column numbers

#drop unnecessary columns such as timestamp and resource
#1:4 means determined index that are not necessary
last_activities = last_activities.drop(list(last_activities.columns)[1:4], axis = 1)

#this function splits the given list a in n parts
#such that splitted sublists have roughly same length
#be used : a : caseids, n : # processes = 4 -> split the list of caseids
def split(a, n):
    
    #the function divmod takes two argument (a1, a2) and returns two results(r1, r2)
    #r1 = a1/a2, r2 = a1 mod a2
    """
    divmod(8, 3) =  (2, 2)
    divmod(7.5, 2.5) =  (3.0, 0.0)
    """
    k, m = divmod(len(a), n)
    return list((a[i*k+min(i, m):(i+1)*k+min(i+1, m)] for i in range(n)))

#filtersingles filter out all the variant with just 1 cases
#be used : l -> list of caseids
def filtersingles(l):
    
    #empty list to collect all the single variant
    singles = []
    
    #start loop
    for i in l:

        #if the length of the given element is 
        if len(i) == 1:
            
            singles.append(i)
            
    return [x for x in l if x not in singles], singles

#this function uses multiprocessing to apply parallel programming paradigm 
def filtersingles_mp(a_list):
    
    PROCESSES = 4
    nonsingles = []
    singles = []
    
    with multiprocessing.Pool(PROCESSES) as pool:
    
        chunks = split(list(a_list), 4)
    
        results = [pool.apply_async(filtersingles, [chunk]) for chunk in chunks]
        
        for r in results:
            
            nonsingles = nonsingles + r.get()[0]
            singles = singles + r.get()[1]
            
    return nonsingles, singles

ns_vci, s_vci = filtersingles_mp(variant_caseid)

def modifyindex(df):
    
    df = df.set_index('Case ID')
    
    return df

In [39]:
def filter_last_activity_catcols(logdf):
    
    result_df = logdf.copy()
    ccols = []
    
    for c in range(len(list(result_df.columns))):
        
        #check if the column is boolean
        if ptypes.is_bool_dtype(list(result_df.columns)[c]) == True:
            
            #then multiply 1 to whole column such that they can be numeric
            #used if else such that each column can be checked with on condition 
            result_df.iloc[:, c] = result_df.iloc[:, c].apply(lambda x: x*1)
        
        #check if a column is numerical
        elif ptypes.is_numeric_dtype(list(result_df.columns)[c]) != True:
            
            #else go into the catcols list
            ccols.append(c)
            
        else :
        
            continue
    
    #result_df keeps just the last activities of each traces
    #keep the index of categorical colums
    return result_df, ccols

last_activities, ccols = filter_last_activity_catcols(last_activities)

#this function returns the dataframe part regarding the given caseid
#be used : splits the log dataframe corresponding the given caseid
def filterdf(logdf, caseid):

    return logdf.loc[logdf["Case ID"].isin(caseid)]

def splitdf(logdf, caseids):

    dfs = []
    
    for ci in caseids:
        
        dfs.append(filterdf(logdf, ci))
        
    return dfs

#this function applies splitdf in multithreading
#logdf : dataframe to be splitted
#caseids : list of caseid (variant_caseid) will be used
def splitdf_mp(logdf, caseids):
    
    # the number of processes
    PROCESSES = 4
    
    #list of dataframes to be returned
    dfs = []
    
    with multiprocessing.Pool(PROCESSES) as pool:
        
        #split caseid into 4 
        chunks = split(list(caseids), 4)
        
        results = [pool.apply_async(splitdf, (logdf, chunk)) for chunk in chunks]
    
        for r in results:
            
            dfs.append(r.get())
            
    return dfs

#subset of dfs corresponding their single variant
#each single element in the list is dataframe
dfs_variant = splitdf_mp(last_activities, ns_vci)


#One hot encoding
#now apply one hot encoding using every categorical colum from the catcols     
#check every list of case id of each variant

#this function applies one hot encoding to the given dataframe regarding the given column names
#df : dataframe to be the one hot encoding applied
#columns : columnnames(should be categorical columns)
def one_hot_encoding(df, columns):
    
    encoded = []
    first_column = df.iloc[:, 0]
    encoded.append(first_column)
    #
    
    for c in range(1,len(columns)):
    
        #one hot encoding of each colum
        encoded.append(pd.get_dummies(df.iloc[:, c], prefix = df.columns[c]))
        
    return pd.concat(encoded, axis=1)

def map_one_hot_encoding(dfs, columns):
    
    one_hot_encoded = []
    
    for i in range(len(dfs)):
        
        one_hot_encoded.append(list(map(functools.partial(one_hot_encoding, columns=columns), dfs[i])))
        
    return one_hot_encoded

dfs_variant = map_one_hot_encoding(dfs_variant, ccols)

def euclidean_distance(df):
    
    #set the Case Id(first column) as index
    df = modifyindex(df)
    #remove all columns having either 1 or 0(do not need to compute in the euclidean distance)  
    df = df.loc[:,~df.eq(0).all()]
    df = df.loc[:,~df.eq(1).all()]

    #add the dist column containing the euclidean distance to every rows
    df['dist']=pd.Series(np.sum(distance.cdist(df.iloc[:,1:], df.iloc[:,1:], metric='euclidean'), axis = 1), index = df.index)
    
    #sort this small dataframe by the dist
    df = df.sort_values(by=['dist'])
    
    #rank this dataframe by the distance
    #frame['sum_order'] = frame['sum'].rank()
    
    df['dist_order'] = df['dist'].rank()
    
    #print(df)
    
    return df['dist_order']

def euclidean_distance_list(dfs):
    
    new_dfs = []
    
    for df in dfs:
        
        new_dfs.append(euclidean_distance(df))
        
    return new_dfs
        
        
#this function computes the euclidean distance using multiprocessing
def euclidean_distance_mp(dfs):
    
    # the number of processes
    PROCESSES = 4
    
    with multiprocessing.Pool(PROCESSES) as pool:
        
        results = pool.map(euclidean_distance_list, dfs)
    
        return results
    
    #return dfs

#k = euclidean_distance(dfs_variant[0][0])
#k = one_hot_encoding(dfs_variant[0][0], ccols)

#one_hot_encoded = map_one_hot_encoding(dfs_variant, ccols)
r = euclidean_distance_mp(dfs_variant)

#return the final case ids
#depending on the selection method, n has different values s.t
# unique selection n -> 1 (default setting)
# logarithmic selection n -> log2( number of traces of each variant)
# division selection n -> round(number of traces of each variant / 2)
def final_caseids(df, n = 1):
    
    df = df.to_frame()
    
    return list(df.head(n).index)
    
    #df.head(n)
    
    #for df_list in dfs:
        
    #    final_caseids = final_caseids + list(map(addition, numbers))
    
def final_caseids_list(dfs, n=1):
    
    return [final_caseids(df, n) for df in dfs]

#r is the final all ranked caseids

def flatten(t):
    return [item for sublist in t for item in sublist]

def final_caseids_mp(dfs, n = 1):
    
    # the number of processes
    PROCESSES = 4
    
    items = list(((df, n) for df in dfs))
    
    #L = pool.starmap(func, [(1, 1), (2, 1), (3, 1)])
    
    with multiprocessing.Pool(PROCESSES) as pool:
        
        #.starmap(f_sum, data)
        results = pool.starmap(final_caseids_list, items)
        
    results = flatten(flatten(results))
    
    #results = [item for sublist in dfs for item in sublist]
    return results
    
final_caseid_list = final_caseids_mp(r)

In [46]:
def export_file(df, caseids, s_vci, n = 1):
    
    #2 indicates that it is logarithmic
    #it is just for now!!!!
    if n != 2:
        
        caseids = caseids + s_vci
    
    export_csv = df[df['Case ID'].isin(caseids)]
    export_csv.to_csv('exported.csv', index = True, header=True)

## How to execute all the functions?

In [47]:
#separate variants between
#ns_vci : NonSingle Variant Case ID
#s_vci : Single Variant Case ID
ns_vci, s_vci = filtersingles_mp(variant_caseid)

#extract just the very last row of each cases and separate Categorical Columns (ccols)
last_activities, ccols = filter_last_activity_catcols(last_activities)

#subset of dfs corresponding their single variant
#each single element in the list is dataframe
dfs_variant = splitdf_mp(last_activities, ns_vci)

#One hot encoding
dfs_variant = map_one_hot_encoding(dfs_variant, ccols)

#euclidean distance is computed and ranked by this
r = euclidean_distance_mp(dfs_variant)

#extract final case ids that passed the euclidean_distance_mp
final_caseid_list = final_caseids_mp(r)

#export the csv file corresponding to the imported csv file
export_file(log_csv, r, s_vci)